channels:
- pytorch
- anaconda
- conda-forge
dependencies:
- python=3.7
- pip=21.1.2
- pip:
  - azureml-core==1.48.0
  - azureml-mlflow==1.48.0
  - azureml-automl-core==1.48.0
  - azureml-automl-dnn-nlp==1.48.0
  - azureml-automl-runtime==1.48.0
  - azureml-train-automl-client==1.48.0
  - azureml-train-automl-runtime==1.48.0
  - azureml-defaults==1.48.0
- numpy~=1.21.6
- pandas~=1.1.5
- shap=0.39.0
- scikit-learn~=0.22.1
#- pytorch==1.7.1
- transformers[sentencepiece]==4.6.0
name: project_environment
